import re
from kipy import KiCad
from kipy.board import Board
from kipy.board_types import Track, ArcTrack, FootprintInstance
from typing import Set, Optional, List, Tuple, DefaultDict
from collections import defaultdict
from kipy.geometry import Vector2
from dataclasses import dataclass, field

@dataclass(frozen=True)
class TrackGroupKey:
    """Immutable identifier key used to group tracks."""
    layer: int
    width: int
    net_name: str

@dataclass
class ConnectionNode:
    """Represents a point (node) on the connectivity graph."""
    tracks: Set[str] = field(default_factory=set)
    is_anchored: bool = False

class KiCadPCB:
    def __init__(self):
        self.kicad: Optional[KiCad] = None
        self.board: Optional[Board] = None
        self.footprints: List[FootprintInstance] = []
        self.connected: bool = False

    def connect_kicad(self) -> Tuple[bool, str]:
        try:
            self.footprints = []
            self.kicad = KiCad()
            self.board = self.kicad.get_board()
            self.footprints = self.board.get_footprints()
            self.footprints.sort(key=natural_sort_key)
            self.connected = True
            return True, "Connected to KiCad"
            
        except Exception as e:
            import traceback
            traceback.print_exc()
            self.connected = False
            self.footprints = []
            self.references = []
            self.stackup = []
            self.layers = []
            return False, str(e)
        
    def check_overlap_and_find_extremities(self, t1: Track, t2: Track, tol=1e-4):
        """
        Applies KiCad C++ Vector Geometry to check for collinearity and overlapping.
        """
        dx1 = t1.end.x - t1.start.x
        dy1 = t1.end.y - t1.start.y
        len_sq = dx1**2 + dy1**2
        
        if len_sq < 1e-6: 
            return False, None, None # Skip if the track is just a point
            
        dx2 = t2.end.x - t2.start.x
        dy2 = t2.end.y - t2.start.y
        
        # 1. Check for parallelism (Cross product == 0)
        if abs(dx1 * dy2 - dy1 * dx2) > tol: 
            return False, None, None
            
        # 2. Check for collinearity
        dx3 = t2.start.x - t1.start.x
        dy3 = t2.start.y - t1.start.y
        if abs(dx1 * dy3 - dy1 * dx3) > tol:
            return False, None, None
            
        # 3. Check for touching/overlapping using parametric equations
        # Assuming T1 runs from t=0 to t=1. Find the interval t of T2 projected onto T1.
        t_C = (dx1 * dx3 + dy1 * dy3) / len_sq
        t_D = (dx1 * (t2.end.x - t1.start.x) + dy1 * (t2.end.y - t1.start.y)) / len_sq
        
        t2_min, t2_max = min(t_C, t_D), max(t_C, t_D)
        
        # If the interval [0, 1] of T1 and [t2_min, t2_max] of T2 intersect
        if max(0, t2_min) <= min(1, t2_max) + 1e-5:
            # Collect all 4 points and project them onto the line to find the 2 furthest points
            points = [t1.start, t1.end, t2.start, t2.end]
            projections = [((p.x - t1.start.x)*dx1 + (p.y - t1.start.y)*dy1, p) for p in points]
            
            # Sort by projection value
            projections.sort(key=lambda item: item[0])
            
            # Return True and the 2 extremities
            return True, projections[0][1], projections[-1][1]
            
        return False, None, None

    def merge_overlapping_tracks(self):
        print("Scanning and merging collinear/overlapping tracks...")
        
        commit = self.board.begin_commit()
        
        items_to_create = []
        items_to_remove = []
        
        # Ledger to store IDs of virtual tracks generated by Python
        virtual_track_ids = set()
        
        tracks = [t for t in self.board.get_tracks() if isinstance(t, Track)]
        track_groups: DefaultDict[TrackGroupKey, List[Track]] = defaultdict(list)
        
        for t in tracks:
            net_name = t.net.name if getattr(t, 'net', None) else ""
            key = TrackGroupKey(layer=t.layer, width=t.width, net_name=net_name)
            track_groups[key].append(t)

        merged_count = 0

        for key, group in track_groups.items():
            while True:
                merged_in_this_pass = False
                i = 0
                while i < len(group):
                    t1 = group[i]
                    merged = False
                    
                    for j in range(i + 1, len(group)):
                        t2 = group[j]
                        
                        is_overlap, ext_start, ext_end = self.check_overlap_and_find_extremities(t1, t2)
                        
                        if is_overlap:
                            new_track = Track() 
                            new_track.start = ext_start
                            new_track.end = ext_end
                            new_track.layer = t1.layer
                            new_track.width = t1.width
                            if hasattr(t1, 'net') and t1.net:
                                new_track.net = t1.net
                            
                            # Record the memory address of this new track into the ledger
                            virtual_track_ids.add(id(new_track))
                            
                            # If t1 is not in the ledger (meaning it's an original track from KiCad) -> add to removal list
                            if id(t1) not in virtual_track_ids:
                                items_to_remove.append(t1)
                            
                            # Same for t2
                            if id(t2) not in virtual_track_ids:
                                items_to_remove.append(t2)
                            
                            group.append(new_track)
                            group.pop(j)
                            group.pop(i)
                            
                            merged = True
                            merged_in_this_pass = True
                            merged_count += 1
                            break 
                    
                    if not merged:
                        i += 1
                
                if not merged_in_this_pass:
                    break 
            
            # Only create tracks whose IDs are in the ledger
            for final_track in group:
                if id(final_track) in virtual_track_ids:
                    items_to_create.append(final_track)

        if items_to_create or items_to_remove:
            try:
                if items_to_create:
                    self.board.create_items(items_to_create)
                if items_to_remove:
                    self.board.remove_items(items_to_remove)
                
                self.board.push_commit(commit, f"Merged {merged_count} collinear/overlapping tracks")
                print(f"Success! Removed {len(items_to_remove)} fragmented segments, recreated {len(items_to_create)} continuous segments.")
            except Exception as e:
                self.board.drop_commit(commit)
                print(f"An error occurred, reverted: {e}")
        else:
            self.board.drop_commit(commit)
            print("No collinear/overlapping tracks to merge.")

    def remove_stubs_recursive(self):
        print("Recursively scanning for stub tracks...")
        
        # THE POWER OF DEFAULTDICT: 
        # If querying a non-existent coordinate, it automatically initializes a ConnectionNode()
        point_map: DefaultDict[Tuple[float, float, int], ConnectionNode] = defaultdict(ConnectionNode)

        # 1. Anchor points using Pads and Vias
        for pad in self.board.get_pads():
            pos = pad.position
            layers = pad.padstack.layers
            for layer in layers:
                # Call the .is_anchored attribute directly, very intuitive
                point_map[get_key(pos, layer)].is_anchored = True

        for via in self.board.get_vias():
            pos = via.position
            layers = via.padstack.layers
            for layer in layers:
                point_map[get_key(pos, layer)].is_anchored = True

        # 2. Add Tracks to the Graph
        tracks = self.board.get_tracks()
        #tracks = [t for t in self.board.get_tracks() if isinstance(t, (Track, ArcTrack))]
        for track in tracks:
            for pos in (track.start, track.end):
                key = get_key(pos, track.layer)
                point_map[key].tracks.add(track.id.value)

        track_dict = {t.id.value: t for t in tracks}

        # 3. Find the initial stubs
        stub_ids = []
        for key, node in point_map.items():
            # Self-documenting code
            if len(node.tracks) == 1 and not node.is_anchored:
                stub_ids.append(list(node.tracks)[0])

        # 4. Recursive shaving algorithm (Iterative Shaving)
        deleted_ids = set()
        
        while stub_ids:
            t_id = stub_ids.pop()
            if t_id in deleted_ids: 
                continue
                
            deleted_ids.add(t_id)
            track = track_dict[t_id]
            
            # Remove this track from both ends of the graph
            for pos in (track.start, track.end):
                key = get_key(pos, track.layer)
                node = point_map[key]
                
                if t_id in node.tracks:
                    node.tracks.remove(t_id)
                
                # RECURSIVE CHECK: Does the inner connection point become a new stub?
                if len(node.tracks) == 1 and not node.is_anchored:
                    remaining_t_id = list(node.tracks)[0]
                    stub_ids.append(remaining_t_id)

        # 5. Batch Execute API
        commit = self.board.begin_commit()
        
        if deleted_ids:
            tracks_to_delete = [track_dict[t_id] for t_id in deleted_ids]
            
            try:
                self.board.remove_items(tracks_to_delete)
                self.board.push_commit(commit, f"Removed {len(tracks_to_delete)} stub tracks")
                print(f"Successfully cleaned {len(tracks_to_delete)} stub tracks (including chained segments).")
            except Exception as e:
                self.board.drop_commit(commit)
                print(f"An error occurred while deleting stubs, reverted: {e}")
        else:
            self.board.drop_commit(commit)
            print("Scan complete. No stub tracks found.")

def natural_sort_key(footprint: FootprintInstance):
    text = footprint.reference_field.text.value
    return [int(c) if c.isdigit() else c.lower() for c in re.split(r'(\d+)', text)]

def get_key(pos: Vector2, layer):
    return (round(pos.x, 4), round(pos.y, 4), layer)