import re
import math
from kipy import KiCad
from kipy.board import Board
from kipy.board_types import Track, ArcTrack, Pad, FootprintInstance
from typing import Set, Optional, List, Tuple, DefaultDict
from collections import defaultdict
from kipy.geometry import Vector2
from dataclasses import dataclass, field

class NetPadMap:
    def __init__(self, name: str):
        self.net_name: str = name
        self.pads: List[Pad] = []

@dataclass(frozen=True)
class TrackGroupKey:
    """Immutable identifier key used to group tracks."""
    layer: int
    width: int
    net_name: str

@dataclass
class ConnectionNode:
    """Represents a point (node) on the connectivity graph."""
    tracks: Set[str] = field(default_factory=set)
    is_anchored: bool = False

class KiCadPCB:
    def __init__(self):
        self.kicad: Optional[KiCad] = None
        self.board: Optional[Board] = None
        self.footprints: List[FootprintInstance] = []
        self.connected: bool = False

    def connect_kicad(self) -> Tuple[bool, str]:
        try:
            self.footprints = []
            self.kicad = KiCad()
            self.board = self.kicad.get_board()
            self.footprints = self.board.get_footprints()
            self.footprints.sort(key=natural_sort_key)
            self.connected = True
            return True, "Connected to KiCad"
            
        except Exception as e:
            import traceback
            traceback.print_exc()
            self.connected = False
            self.footprints = []
            self.references = []
            self.stackup = []
            self.layers = []
            return False, str(e)
        
    def check_overlap_and_find_extremities(self, t1: Track, t2: Track, tol_deg=0.1):
        """
        Applies normalized Vector Geometry to mitigate nanometer rounding errors.
        tol_deg: Maximum angular deviation allowed to consider 2 tracks collinear (Default 0.1 degrees).
        """
        import math
        
        dx1 = t1.end.x - t1.start.x
        dy1 = t1.end.y - t1.start.y
        len1 = math.hypot(dx1, dy1)
        
        if len1 < 1e-6: 
            return False, None, None 
            
        dx2 = t2.end.x - t2.start.x
        dy2 = t2.end.y - t2.start.y
        len2 = math.hypot(dx2, dy2)
        
        if len2 < 1e-6:
            return False, None, None

        # Convert angular tolerance from degrees to Radians for comparison with sin(theta)
        tol_rad = math.radians(tol_deg)

        # 1. Check parallelism using Normalized Cross Product (Calculates sin of the deviation angle)
        cross_1 = dx1 * dy2 - dy1 * dx2
        sin_theta1 = cross_1 / (len1 * len2)
        
        if abs(sin_theta1) > tol_rad: 
            return False, None, None
            
        # 2. Check collinearity
        dx3 = t2.start.x - t1.start.x
        dy3 = t2.start.y - t1.start.y
        len3 = math.hypot(dx3, dy3)
        
        # Only check collinearity if the starting points of the 2 tracks do not perfectly overlap
        if len3 > 1e-6:
            cross_2 = dx1 * dy3 - dy1 * dx3
            sin_theta2 = cross_2 / (len1 * len3)
            if abs(sin_theta2) > tol_rad:
                return False, None, None
            
        # 3. Check for touching/overlapping using parametric equations
        len_sq = len1 ** 2
        t_C = (dx1 * dx3 + dy1 * dy3) / len_sq
        t_D = (dx1 * (t2.end.x - t1.start.x) + dy1 * (t2.end.y - t1.start.y)) / len_sq
        
        t2_min, t2_max = min(t_C, t_D), max(t_C, t_D)
        
        # Accept intersection exactly at the extremities (t=0 or t=1) with a 1e-4 tolerance
        if max(0.0, t2_min) <= min(1.0, t2_max) + 1e-4:
            points = [t1.start, t1.end, t2.start, t2.end]
            projections = [((p.x - t1.start.x)*dx1 + (p.y - t1.start.y)*dy1, p) for p in points]
            
            projections.sort(key=lambda item: item[0])
            return True, projections[0][1], projections[-1][1]
            
        return False, None, None

    def merge_overlapping_tracks(self):
        print("Scanning and merging collinear/overlapping tracks...")
        
        commit = self.board.begin_commit()
        
        items_to_create = []
        items_to_remove = []
        
        # Ledger to store IDs of virtual tracks generated by Python
        virtual_track_ids = set()
        
        tracks = [t for t in self.board.get_tracks() if isinstance(t, Track)]
        track_groups: DefaultDict[TrackGroupKey, List[Track]] = defaultdict(list)
        
        for t in tracks:
            net_name = t.net.name if getattr(t, 'net', None) else ""
            key = TrackGroupKey(layer=t.layer, width=t.width, net_name=net_name)
            track_groups[key].append(t)

        merged_count = 0

        for key, group in track_groups.items():
            while True:
                merged_in_this_pass = False
                i = 0
                while i < len(group):
                    t1 = group[i]
                    merged = False
                    
                    for j in range(i + 1, len(group)):
                        t2 = group[j]
                        
                        is_overlap, ext_start, ext_end = self.check_overlap_and_find_extremities(t1, t2)
                        
                        if is_overlap:
                            new_track = Track() 
                            new_track.start = ext_start
                            new_track.end = ext_end
                            new_track.layer = t1.layer
                            new_track.width = t1.width
                            if hasattr(t1, 'net') and t1.net:
                                new_track.net = t1.net
                            
                            # Record the memory address of this new track into the ledger
                            virtual_track_ids.add(id(new_track))
                            
                            # If t1 is not in the ledger (meaning it's an original track from KiCad) -> add to removal list
                            if id(t1) not in virtual_track_ids:
                                items_to_remove.append(t1)
                            
                            # Same for t2
                            if id(t2) not in virtual_track_ids:
                                items_to_remove.append(t2)
                            
                            group.append(new_track)
                            group.pop(j)
                            group.pop(i)
                            
                            merged = True
                            merged_in_this_pass = True
                            merged_count += 1
                            break 
                    
                    if not merged:
                        i += 1
                
                if not merged_in_this_pass:
                    break 
            
            # Only create tracks whose IDs are in the ledger
            for final_track in group:
                if id(final_track) in virtual_track_ids:
                    items_to_create.append(final_track)

        if items_to_create or items_to_remove:
            try:
                if items_to_create:
                    self.board.create_items(items_to_create)
                if items_to_remove:
                    self.board.remove_items(items_to_remove)
                
                self.board.push_commit(commit, f"Merged {merged_count} collinear/overlapping tracks")
                print(f"Success! Removed {len(items_to_remove)} fragmented segments, recreated {len(items_to_create)} continuous segments.")
            except Exception as e:
                self.board.drop_commit(commit)
                print(f"An error occurred, reverted: {e}")
        else:
            self.board.drop_commit(commit)
            print("No collinear/overlapping tracks to merge.")

    def remove_stubs_recursive(self):
        point_map: DefaultDict[Tuple[float, float, int], ConnectionNode] = defaultdict(ConnectionNode)

        # ==========================================
        # 1. Anchor points using Pads and Vias
        # ==========================================
        
        # Initialize list based on desired structure
        pads_by_net: List[NetPadMap] = []
        
        for pad in self.board.get_pads():
            net_name = pad.net.name if getattr(pad, 'net', None) else ""
            
            # Scan array to see if a NetPadMap object for this net_name already exists
            target_net_map = None
            for net_map in pads_by_net:
                if net_map.net_name == net_name:
                    target_net_map = net_map
                    break
            
            # If it doesn't exist, create it and insert into the array
            if not target_net_map:
                target_net_map = NetPadMap(net_name)
                pads_by_net.append(target_net_map)
                
            # Append pad to the inner array of the object
            target_net_map.pads.append(pad)
            
            pos = pad.position
            layers = pad.padstack.layers
            for layer in layers:
                point_map[get_key(pos, layer)].is_anchored = True

        for via in self.board.get_vias():
            pos = via.position
            layers = via.padstack.layers
            for layer in layers:
                point_map[get_key(pos, layer)].is_anchored = True

        # ==========================================
        # 2. Add Tracks to the Graph
        # ==========================================
        tracks = [t for t in self.board.get_tracks() if isinstance(t, (Track, ArcTrack))]
        
        for track in tracks:
            net_name = track.net.name if getattr(track, 'net', None) else ""
            
            # Scan array to get the Pad list of the corresponding Net
            item_pads = []
            for net_map in pads_by_net:
                if net_map.net_name == net_name:
                    item_pads = net_map.pads
                    break
            
            for pos in (track.start, track.end):
                key = get_key(pos, track.layer)
                node = point_map[key]
                node.tracks.add(track.id.value)
                
                # Bounding Box Check
                if not node.is_anchored and item_pads:
                    for pad in item_pads:
                        if track.layer in pad.padstack.layers:
                            w, h = 0, 0
                            if pad.padstack.copper_layers:
                                pad_size = pad.padstack.copper_layers[0].size
                                w = pad_size.x
                                h = pad_size.y
                            
                            dx = abs(pos.x - pad.position.x)
                            dy = abs(pos.y - pad.position.y)
                            
                            if dx <= (w / 2.0) + 10000 and dy <= (h / 2.0) + 10000:
                                node.is_anchored = True
                                break
        print("Recursively scanning for stub tracks done")
    
    def breakout_diff_pair(self, width_nm=250000, gap_nm=200000, escape_length=2000000, escape_mode="Perpendicular", flip_direction=False) -> int:
        """
        Automates differential pair breakout.
        escape_mode: Supported modes include: 
                     "Perpendicular", "0 Degrees", "22.5 Degrees", "45 Degrees", 
                     "67.5 Degrees", "90 Degrees", "-22.5 Degrees", "-45 Degrees", 
                     "-67.5 Degrees", "-90 Degrees".
        """
        print(f"Processing Differential Pair Breakout (Mode: {escape_mode})...")
        
        selected_items = self.board.get_selection()
        selected_pads = [item for item in selected_items if isinstance(item, Pad)]
        
        if len(selected_pads) != 2:
            print(f"Error: Exactly 2 pads must be selected. (Currently selected: {len(selected_pads)})")
            return 2
            
        pad1, pad2 = selected_pads[0], selected_pads[1]
        layer = pad1.padstack.layers[0] if hasattr(pad1, 'padstack') else 0
        
        x1, y1 = pad1.position.x, pad1.position.y
        x2, y2 = pad2.position.x, pad2.position.y
        
        # 1. Calculate the vector connecting the centers of the 2 pads
        vx = x2 - x1
        vy = y2 - y1
        dist = math.hypot(vx, vy)
        
        if dist < 1e-6:
            print("Error: Pads have identical coordinates.")
            return 0
            
        # Unit vectors ux, uy
        ux = vx / dist
        uy = vy / dist
        
        # Midpoint coordinates of the 2 pads
        mx = (x1 + x2) / 2.0
        my = (y1 + y2) / 2.0
        
        pitch = width_nm + gap_nm
        
        # 2. Analyze the escape direction vector
        mode_str = str(escape_mode).strip().lower()
        if mode_str == 'perpendicular':
            px = -uy
            py = ux
        else:
            try:
                # Trích xuất con số từ các chuỗi như "22.5 Degrees", "-45 Degrees"
                angle_str = mode_str.replace("degrees", "").replace("degree", "").strip()
                angle_deg = float(angle_str)
                rad = math.radians(angle_deg)
                px = math.cos(rad)
                py = math.sin(rad)
            except ValueError:
                # Fallback to perpendicular if parsing fails
                px = -uy
                py = ux
                
        # Handle flip direction
        if flip_direction:
            px = -px
            py = -py
            
        # Normal vector of the escape path to calculate gap compensation
        nx = -py
        ny = px
        
        # Calculate the projection of the 2-pad vector onto the normal vector
        dot_product = abs(ux * nx + uy * ny)
        
        if dot_product < 0.05: # Too parallel, cannot create the required gap
            print("Error: The chosen escape angle is too parallel to the pads. Cannot maintain differential gap.")
            return 0
            
        # 3. Extend the breakout distance to ensure the gap is exactly maintained
        collinear_dist = pitch / dot_product
        
        if dist <= collinear_dist:
            print("Error: The pads are too close to breakout at this angle while maintaining the gap.")
            return 0
            
        # 4. Determine the 2 turning points (T1, T2)
        t1_x = mx - (collinear_dist / 2.0) * ux
        t1_y = my - (collinear_dist / 2.0) * uy
        
        t2_x = mx + (collinear_dist / 2.0) * ux
        t2_y = my + (collinear_dist / 2.0) * uy
        
        # 5. Determine the escape endpoints (E1, E2)
        e1_x = t1_x + escape_length * px
        e1_y = t1_y + escape_length * py
        
        e2_x = t2_x + escape_length * px
        e2_y = t2_y + escape_length * py
        
        items_to_create = []
        commit = self.board.begin_commit()
        
        try:
            # --- PAD 1 ROUTING ---
            t1_in = Track()
            t1_in.start = Vector2.from_xy(int(x1), int(y1))
            t1_in.end = Vector2.from_xy(int(t1_x), int(t1_y))
            t1_in.width, t1_in.layer = width_nm, layer
            if hasattr(pad1, 'net'): t1_in.net = pad1.net
            items_to_create.append(t1_in)
            
            t1_out = Track()
            t1_out.start = Vector2.from_xy(int(t1_x), int(t1_y))
            t1_out.end = Vector2.from_xy(int(e1_x), int(e1_y))
            t1_out.width, t1_out.layer = width_nm, layer
            if hasattr(pad1, 'net'): t1_out.net = pad1.net
            items_to_create.append(t1_out)
            
            # --- PAD 2 ROUTING ---
            t2_in = Track()
            t2_in.start = Vector2.from_xy(int(x2), int(y2))
            t2_in.end = Vector2.from_xy(int(t2_x), int(t2_y))
            t2_in.width, t2_in.layer = width_nm, layer
            if hasattr(pad2, 'net'): t2_in.net = pad2.net
            items_to_create.append(t2_in)
            
            t2_out = Track()
            t2_out.start = Vector2.from_xy(int(t2_x), int(t2_y))
            t2_out.end = Vector2.from_xy(int(e2_x), int(e2_y))
            t2_out.width, t2_out.layer = width_nm, layer
            if hasattr(pad2, 'net'): t2_out.net = pad2.net
            items_to_create.append(t2_out)
            
            self.board.create_items(items_to_create)
            self.board.push_commit(commit, "Auto Diff Pair Breakout")
            print(f"Successfully created differential pair breakout at {escape_mode}.")
            return 1
            
        except Exception as e:
            self.board.drop_commit(commit)
            print(f"Error creating tracks: {e}")
            return 0

def natural_sort_key(footprint: FootprintInstance):
    text = footprint.reference_field.text.value
    return [int(c) if c.isdigit() else c.lower() for c in re.split(r'(\d+)', text)]

def get_key(pos: Vector2, layer):
    return (round(pos.x, 4), round(pos.y, 4), layer)
